//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stefaniniTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int transaction_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public int transaction_type { get; set; }
        public int transaction_origin_account_id { get; set; }
        public Nullable<int> transaction_target_account_id { get; set; }
        public string transactions_description { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual accounts accounts1 { get; set; }
        public virtual transactions_type transactions_type { get; set; }
    }
}
